config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  # Defines the root path route ("/")
  # root "articles#index"
  # resources :users, only: [:show]
  # resources :users, only: [:show, :edit, :update]
  # resources :posts, only: [:new, :create, :show, :destroy]
  resources :users
  resources :follows, only: [:create, :destroy]
  resources :posts do
    resources :comments
  end
  resources :users do
    member do
      get :followers, :followings, :given_follows, :received_follows
    end
  end
  resources :users do
    member do
      patch :follow
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
    # The user following 
  belongs_to :follower, foreign_key: :follower_id, class_name: "User"

  # The user being followed
  belongs_to :followed_user, foreign_key: :followed_user_id, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_one_attached :image

    validate :image_presence
    def image_presence
        errors.add(:image, "can't be blank") unless image.attached?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  # Will return an array of follow instances where (A,B(current user)), (C,B), (D,B)
  has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow", dependent: :destroy

  # Will return an array of (A,C,D) users who follow B(current user)
  has_many :followers, through: :received_follows, source: :follower
# ------------------------------------------------------------------
  # returns an array of follow objects where (B,A), (B,C), (B,D) 
  has_many :given_follows, foreign_key: :follower_id, class_name: "Follow", dependent: :destroy
  
  # returns an array of (A,C,D)-> users who are followed by B(current user)
  has_many :followings, through: :given_follows, source: :followed_user

  def follow(other_user) 
    self.given_follows.create(followed_user_id: other_user.id)
  end
 
# Unfollows a user.
  def unfollow(other_user)
      self.given_follows.find_by(followed_user_id: other_user.id).destroy
  end
 
# Returns true if the current user is following the other user.
  def following_c(other_user)
      following.include?(other_user)
  end
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def comment_params
        params.require(:comment).permit(:post_id, :txt)
    end
    def create
        # @comment = Comment.new(comment_params)
        @post = Post.find(params[:post_id])
        # @comment = @post.comments.build(params[:comment].permit(:txt))
        @comment = @post.comments.build(comment_params)
        @comment.user_id = current_user.id
        @comment.save!
   
        # respond_to do |format|
        #   if @comment.save
            # format.html { redirect_to @comment.post, notice: "Comment was successfully created." }
        #   else
        #     format.html { render :new, status: :unprocessable_entity }
        #   end
        # end
        redirect_to @post
    end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    def create
        @user = User.find(params[:followed_user_id])
        current_user.follow(@user)
        redirect_to @user
      end
    
      def destroy
        @user = Follow.find(params[:id]).followed_user
        current_user.unfollow(@user)
        redirect_to @user
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @all_users = current_user.followings
      unless @all_users.include?(current_user)
        @all_users.push(current_user)
      end
      @posts = Post.where(:user_id => @all_users).order(created_at: :desc).page(params[:page]).per(5)
      
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def destroy
        @post = current_user.posts.find(params[:id])
        @post.destroy
        redirect_to user_path(current_user)
    end
    def show
        @post = Post.find(params[:id])
        @comment = @post.comments.build
    end
    def create
        Post.create(post_params)
        redirect_to root_path
      end
      private
      def post_params
        params.require(:post).permit(:caption, :image, :user_id)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verify_authenticity_token
    def show
        @user  = User.find(params[:id])
        @posts = @user.posts.order(created_at: :desc)
    end
    
    def edit
        @user = User.find(params[:id])
    end
    def update
        current_user.update(user_params)
        redirect_to current_user
    end
      private
      def user_params
        params.require(:user).permit(:username, :name,
                                     :bio, :email, :phone, :avatar)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_upload_form.html.erb
<%= form_with(model: [@post, @post.comments.build]) do |f| %>
                 <%= f.hidden_field :post_id %>
                <%= f.text_area :txt %>

                <div class="actions">
                    <%= f.submit %>
                </div> 
            <% end %>

app/views/home/index.html.erb
<h1>This is my timeline</h1>
<div class="homepage">
    <%= stylesheet_link_tag "posts" %>
    <div>
        <% if user_signed_in? %>
        <div class = "form-upload">
            <%= form_for Post.new do |f| %>
            <div class="form-group">
                <%= f.text_field :caption %>
            </div>
            <div class="form-group">
                <%= f.file_field :image %>
            </div>
            <div class="form-group">
                <%= f.text_field :user_id, value: current_user.id, class:'d-none'%>
            </div>
            <br>
            <div class="text-center">
                <%= f.submit 'Create Post', class: 'btn btn-primary' %>
            </div>
            <% end %>
        </div>
        <% end %>
    </div>
    <div class="posts">
    <% @posts.each do |post| %>
        <section class="post">
            <div class="user">
                <div class="avatar">
                    <% if post.user.avatar.attached? %>
                        <%= link_to user_path(post.user) do %>
                            <%= image_tag post.user.avatar %>
                        <% end %>
                    <% end %>
                </div>
                <%= link_to post.user.username, user_path(post.user), class: 'username' %>
            </div>
            <%= image_tag post.image, class: 'main-image' %>
            <div class="description">
                <%= post.caption %>
            </div>
            
        </section>
    <% end %>
    <%= paginate @posts %>
    </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="#">
            <%= fa_stacked_icon "camera inverse", base: "circle"%>
            Instagram
          </a>
        </div>
        <div class="m-auto">
          <form class="form-inline search-form">
            <input class="form-control mr-sm-2" type="search" placeholder="@search" aria-label="Search">
          </form>
        </div>
        <div class="user-section">
          <a><i class="fa fa-compass"></i></a>
          <a><i class="fa fa-heart"></i></a>
          <% if user_signed_in? %>
            <a href="<%= user_path(current_user)%>">
              <i class="fa fa-user"></i>
            </a>
          <% else %>
            <a href="<%= new_user_session_path%>">
              <i class="fa fa-sign-in"></i>
            </a>
          <% end %>
        </div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US
          </li>
          <li>SUPPORT</li>
          <li>PRESS</li>
          <li>API</li>
          <li>JOBS</li>
          <li>PRIVACY</li>
          <li>TERMS</li>
          <li>DIRECTORY</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
        </ul>
        <p> © 2018 INSTAGRAM </p>
      </nav>
    </footer>
  </body>
</html>

app/views/posts/show.html.erb
<div class="post-show row">
  <div class="col-md-8">
    <%=image_tag @post.image, class: 'image' %>
  </div>
  <div class="col-md-4">
    <div class="user">
      <div class="avatar">
        <% if @post.user.avatar.attached? %>
          <%= link_to user_path(@post.user) do %>
            <%= image_tag @post.user.avatar %>
          <% end %>
        <% end %>
      </div>
      <%= link_to @post.user.username, user_path(@post.user), class: 'username' %>
    </div>
    <div class="description">
<%= @post.caption%>
    </div>
    <div>
        <div>
            <u><b>Comments</b></u>
            <br>
            <%- @post.comments.each do |comment|%>             
                <b><%= comment.user&.username%> </b>
                <%= comment.txt %>
                <br>
            <% end %>
        </div>
        <div>

            <%= render "comments/upload_form", comment: @comment%>  

            
        </div>
    </div>
    <div class="delete">
      <% if current_user.posts.exists?(@post.id) %>
        <%= button_to 'Remove', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
      <a class="nav-link" data-toggle="pill">Change Password</a>
      <a class="nav-link" data-toggle="pill">Authorized Applications</a>
      <a class="nav-link" data-toggle="pill">Email and SMS</a>
      <a class="nav-link" data-toggle="pill">Manage Contacts</a>
      <a class="nav-link" data-toggle="pill">Privacy and Security</a>
      <%= link_to 'Log Out', destroy_user_session_path, :method => :delete, class: "nav-link" %>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
  
  <div class="form-group row">
    <div class="col-sm-3 col-form-label">
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar, class: 'avatar' %>
      <%end %>
    </div>
    <div class="col-sm-9">
      <p class="username"><%=current_user.username %></p>
      <a class="change-photo" href="">Change Profile Photo</a>
    </div>
  </div>
  <div class="form-group row">
  <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
  <div class="col-sm-9">
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
</div>
  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :username, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :username, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_area :bio, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :email, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :phone, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :phone, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-9">
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if @user.avatar.attached? %>
            <%= image_tag @user.avatar %>
        <%end %>
        </div>
    </div>
    
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.username %></h2>
        <% if current_user == @user %>
            <a class="edit-profile" href="<%= edit_user_path(current_user) %>">
                <button>Edit Profile</button>
            </a>
        <% end %>
        <% unless current_user==@user %>
            <div id="follow_form">
                <% if current_user.followings.include?(@user) %>
                    <%= form_with(model: current_user.given_follows.find_by(followed_user_id: @user.id),
                    html: { method: :delete },remote: true) do |f| %>
                    <%= f.submit "Unfollow", class: "btn btn-secondary mx-5" %>
                    <% end %>
                <% else %>
                    <%= form_with(model: current_user.given_follows.create, local: false) do |f| %>
                        <div>
                            <%
=begin%>
 <%= f.text_field :followed_user_id, value: @user.id, class:'d-none'%> 
<%
=end%>
                            <%= hidden_field_tag :followed_user_id, @user.id %> 

                        </div>
                        <%= f.submit "Follow", class: "btn btn-primary" %>
                    <% end %>
                <% end %>
            </div>
        <% end %>
      </div>
      <ul class="posts">
        <li><span><%= @user.posts.count %></span> posts</li>
        <li><span><%= @user.followers.size - 1 %></span> followers</li>
        <li><span><%= @user.followings.size - 1 %></span> following</li>
      </ul>
      <h2 class="name"><%= @user.name %></h2>
    </div>
  </div>
  <div class="user-tabs">
    <a class="tab active" href="">
      <i class="fa fa-th"></i>
      POSTS
    </a>
    <a class="tab" href="">
      <i class="fa fa-tv"></i>
      IGTV
    </a>
    <a class="tab" href="">
      <i class="fa fa-bookmark"></i>
      SAVED
    </a>
    <a class="tab" href="">
      <i class="fa fa-tag"></i>
      TAGGED
    </a>
  </div>

  <div class="user-images">
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%=link_to post_path(post) do %>
          <%=image_tag post.image %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>